# Generated by Django 5.1.6 on 2025-05-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_agency_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
